[package]
name = "bridget-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-support = []

[dependencies]
uuid.workspace = true
bridget-core = { path = "../bridget-core" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
log = { workspace = true }
libc.workspace = true
tungstenite = { version = "0.26.2", default-features = false, features = ["handshake"] }
